import { FormEvent, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const apiUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:3001/api';
type User = { id: number; username: string; name: string; role: string; active: boolean };
type Process = { id: number; code: string; title: string; status: string; createdAt: string; _count?: { files: number; analyses: number } };
type Detail = Process & { files: Array<{ id: number; originalName: string; mimeType: string; sizeBytes: number }>; analyses: Array<{ id: number; status: string; result?: unknown; error?: string }> };

function App() {
  const [user, setUser] = useState<User | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [processes, setProcesses] = useState<Process[]>([]);
  const [selected, setSelected] = useState<Detail | null>(null);
  const [message, setMessage] = useState('');
  const request = async (path: string, options: RequestInit = {}) => {
    const response = await fetch(`${apiUrl}${path}`, { ...options, credentials: 'include', headers: { ...(options.headers ?? {}) } });
    const payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? 'La solicitud falló.'); return payload;
  };
  const refresh = async () => { try { const currentUser = await request('/auth/me'); setUser(currentUser); const processPage = await request('/processes'); setProcesses(processPage.items); if (currentUser.role === 'admin') { const userPage = await request('/users'); setUsers(userPage.items); } } catch { setUser(null); setSelected(null); } };
  useEffect(() => { void refresh(); }, []);
  const logout = async () => { try { await request('/auth/logout', { method: 'POST' }); } finally { setUser(null); setSelected(null); setProcesses([]); } };
  const openProcess = async (id: number) => { try { setSelected(await request(`/processes/${id}`)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  const login = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const data = await fetch(`${apiUrl}/auth/login`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: form.get('username'), password: form.get('password') }) }).then(async r => { const p = await r.json(); if (!r.ok) throw new Error(p.message); return p; }); setUser(data.user); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  const createProcess = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const title = String(new FormData(event.currentTarget).get('title')); try { const process = await request('/processes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title }) }); event.currentTarget.reset(); await refresh(); await openProcess(process.id); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  const createUser = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request('/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: form.get('username'), name: form.get('name'), password: form.get('password'), role: form.get('role') }) }); event.currentTarget.reset(); await refresh(); setMessage('Usuario creado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); try { await request(`/processes/${selected.id}/files`, { method: 'POST', body: form }); event.currentTarget.reset(); await openProcess(selected.id); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  const analyze = async (fileId?: number) => { if (!selected) return; try { const analysis = await request(`/processes/${selected.id}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileId }) }); setMessage(analysis.status === 'completed' ? 'Análisis completado.' : `Análisis falló: ${analysis.error}`); await openProcess(selected.id); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  const download = async (fileId: number, name: string) => { try { const response = await fetch(`${apiUrl}/files/${fileId}/download`, { credentials: 'include' }); if (!response.ok) throw new Error('No se pudo descargar el archivo.'); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error'); } };
  if (!user) return <main className="login"><form onSubmit={login}><h1>Node2</h1><p>Procesos y análisis IA</p><input name="username" placeholder="Usuario" required /><input name="password" type="password" placeholder="Contraseña" required /><button>Ingresar</button>{message && <small>{message}</small>}</form></main>;
  return <main><header><div><strong>Node2</strong><span>{user.name} · {user.role}</span></div><button onClick={logout}>Salir</button></header>{message && <p className="notice">{message}</p>}{user.role === 'admin' && <section className="users"><h2>Usuarios</h2><form onSubmit={createUser} className="inline"><input name="name" placeholder="Nombre" required /><input name="username" placeholder="Usuario" required /><input name="password" type="password" minLength={10} placeholder="Contraseña" required /><select name="role" defaultValue="operator"><option value="operator">Operador</option><option value="admin">Administrador</option></select><button>Crear usuario</button></form><small>{users.map(item => `${item.name} (${item.username}, ${item.role})`).join(' · ')}</small></section>}<section className="grid"><aside><h2>Procesos</h2><form onSubmit={createProcess} className="inline"><input name="title" placeholder="Nombre del proceso" required /><button>Crear</button></form><ul>{processes.map(process => <li key={process.id}><button className="process" onClick={() => void openProcess(process.id)}><b>{process.code}</b><span>{process.title}</span><small>{process.status} · {process._count?.files ?? 0} archivos</small></button></li>)}</ul></aside><article>{selected ? <><h2>{selected.title}</h2><p>{selected.code} · {selected.status}</p><h3>Archivos</h3><form onSubmit={upload} className="inline"><input name="file" type="file" accept=".pdf,.txt,.csv,.json,.jpg,.jpeg,.png" required /><button>Subir</button></form><ul>{selected.files.map(file => <li key={file.id}><button onClick={() => void download(file.id, file.originalName)}>{file.originalName}</button><button onClick={() => void analyze(file.id)}>Analizar IA</button></li>)}</ul><h3>Resultados</h3>{selected.analyses.map(item => <details key={item.id}><summary>{item.status}</summary><pre>{JSON.stringify(item.result ?? { error: item.error }, null, 2)}</pre></details>)}</> : <p>Selecciona o crea un proceso.</p>}</article></section></main>;
}
createRoot(document.getElementById('root')!).render(<App />);
